import java.util.stream.Collectors

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.gradle.publish:plugin-publish-plugin:2.1.1'
        classpath 'com.palantir.baseline-error-prone:gradle-baseline-error-prone:0.17.0'
        classpath 'com.palantir.baseline:gradle-baseline-java:7.5.0'
        classpath 'com.palantir.gradle.consistentversions:gradle-consistent-versions:3.15.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.35.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.18.0'
        classpath 'com.palantir.gradle.gitversion:gradle-git-version:5.0.0'
        classpath 'com.palantir.gradle.guide:gradle-guide:1.29.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.8.0'
        classpath 'com.palantir.gradle.idea-language-injector:gradle-idea-language-injector:0.2.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.79.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.27.0'
        classpath 'com.palantir.gradle.plugintesting:gradle-plugin-testing:0.71.0'
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.6.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.90.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.31.0'
    }
}

apply plugin: 'com.palantir.external-publish'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-error-prone-root'
apply plugin: 'com.palantir.git-version'
apply plugin: 'com.palantir.gradle-guide'
apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'com.palantir.idea-language-injector'
apply plugin: 'com.palantir.consistent-versions'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.external-publish-gradle-plugin'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.jdks.latest'

dependencies {
    implementation 'org.revapi:revapi-basic-features'
    implementation 'org.revapi:revapi-java'
    implementation 'org.revapi:revapi-reporter-text'
    implementation 'org.freemarker:freemarker'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
    implementation 'com.google.guava:guava'

    testImplementation platform('org.junit:junit-bom')
    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.assertj:assertj-core'
    testRuntimeOnly "org.junit.vintage:junit-vintage-engine"

    gradlePluginForTesting 'com.palantir.baseline:gradle-baseline-java'
    gradlePluginForTesting 'com.palantir.gradle.conjure:gradle-conjure'
    gradlePluginForTesting 'com.palantir.gradle.gitversion:gradle-git-version'

    annotationProcessor "org.immutables:value"
    annotationProcessor "org.immutables:serial"
    compileOnly "org.immutables:value::annotations"
    compileOnly "org.immutables:serial"
}

allprojects {
    apply plugin: 'com.palantir.java-format'
    apply plugin: 'com.palantir.jakarta-package-alignment'

    repositories {
        mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
        gradlePluginPortal() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
    }

    group 'com.palantir.gradle.revapi'
    version gitVersion()
}

javaVersions {
    javaCompiler = 25
    libraryTarget = 17
}

jdks {
    daemonTarget = 21
}

test {
    environment = System.getenv().entrySet().stream()
            .filter { entry -> entry.key != 'CIRCLE_TEST_REPORTS' }
            .collect(Collectors.toMap({ it.key }, { it.value }))
}

gradlePlugin {
    website = 'https://github.com/palantir/gradle-revapi'
    vcsUrl = 'https://github.com/palantir/gradle-revapi'

    plugins {
        revapi {
            id = 'com.palantir.revapi'
            implementationClass = 'com.palantir.gradle.revapi.RevapiPlugin'
            description = 'API/ABI backwards compatibility for Java libraries using Revapi'
            displayName = 'API/ABI backwards compatibility for Java libraries using Revapi'
            tags.set(['java', 'versions'])
        }
    }
}

gradleTestUtils {
    configurationCacheEnabled = true
}
